#############################################################################
# Makefile for building: tester
# Generated by qmake (2.01a) (Qt 4.8.0) on: ?? 3. ??? 01:31:50 2013
# Project:  tester.pro
# Template: subdirs
# Command: d:/qtsdk/desktop/qt/4.8.0/mingw/bin/qmake.exe -spec ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o Makefile tester.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:/qtsdk/desktop/qt/4.8.0/mingw/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-library \
		sub-demo

library/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) library/ || $(MKDIR) library/ 
	cd library/ && $(QMAKE) d:/project/tester/library/library.pro -spec ../../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-library-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) library/ || $(MKDIR) library/ 
	cd library/ && $(QMAKE) d:/project/tester/library/library.pro -spec ../../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-library: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE)
sub-library-make_default: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) 
sub-library-make_first: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) first
sub-library-all: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) all
sub-library-clean: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) clean
sub-library-distclean: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) distclean
sub-library-install_subtargets: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) install
sub-library-uninstall_subtargets: library/$(MAKEFILE) FORCE
	cd library/ && $(MAKE) -f $(MAKEFILE) uninstall
demo/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) d:/project/tester/demo/demo.pro -spec ../../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-demo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) d:/project/tester/demo/demo.pro -spec ../../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-demo: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE)
sub-demo-make_default: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) 
sub-demo-make_first: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) first
sub-demo-all: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) all
sub-demo-clean: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) clean
sub-demo-distclean: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demo-install_subtargets: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) install
sub-demo-uninstall_subtargets: demo/$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: tester.pro  ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug_and_release.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/rtti.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/exceptions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/stl.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/shared.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/windows.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o Makefile tester.pro
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug_and_release.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/rtti.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/exceptions.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/stl.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/shared.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/thread.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/windows.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++ CONFIG+=declarative_debug -o Makefile tester.pro

qmake_all: sub-library-qmake_all sub-demo-qmake_all FORCE

make_default: sub-library-make_default sub-demo-make_default FORCE
make_first: sub-library-make_first sub-demo-make_first FORCE
all: sub-library-all sub-demo-all FORCE
clean: sub-library-clean sub-demo-clean FORCE
distclean: sub-library-distclean sub-demo-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-library-install_subtargets sub-demo-install_subtargets FORCE
uninstall_subtargets: sub-library-uninstall_subtargets sub-demo-uninstall_subtargets FORCE

sub-library-sub_Debug: library/$(MAKEFILE)
	cd library/ && $(MAKE) -f $(MAKEFILE) debug
sub-demo-sub_Debug: demo/$(MAKEFILE)
	cd demo/ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-library-sub_Debug sub-demo-sub_Debug

sub-library-sub_Release: library/$(MAKEFILE)
	cd library/ && $(MAKE) -f $(MAKEFILE) release
sub-demo-sub_Release: demo/$(MAKEFILE)
	cd demo/ && $(MAKE) -f $(MAKEFILE) release
release: sub-library-sub_Release sub-demo-sub_Release

sub-library-check: library/$(MAKEFILE)
	cd library/ && $(MAKE) -f $(MAKEFILE) check
sub-demo-check: demo/$(MAKEFILE)
	cd demo/ && $(MAKE) -f $(MAKEFILE) check
check: sub-library-check sub-demo-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

