#ifndef TESTERPLUGIN_GLOBAL_H
#define TESTERPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(TESTERPLUGIN_LIBRARY)
#  define TESTERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTERPLUGIN_GLOBAL_H

